### ISSUE TITLE
Trying to read this using java protobufs

### ISSUE THREAD

**Issue by davecramer** [xstevens/decoderbufs#5]
Hi,

I removed the Postgis code out of this and built it. Trying to read the RowMessage using protocol buffers
Essentially RowMessage.parser(byte[]) getting invalid end tag.

Is ever message a RowMessage ?

**Comment by xstevens** [comment]
Yeah, all messages are RowMessage.

It's been a long time since I played with this. 

The two things I would suggest looking into:

* Make sure your protocol buffer versions match between C and Java
* Make sure there's not any leading or trailing bytes around protocol buffer payload (probably have to serialize your expected payload and then look at the bytes from wireshark or something)

Sorry I can't be of more help on this one.
